START_COMMAND = 'start'

START_BUTTON_TITLE = 'Найти домашнюю группу'
MOSCOW_BUTTON_TITLE = 'Москва'
MO_BUTTON_TITLE = 'МО'
ONLINE_BUTTON_TITLE = 'Онлайн'

METRO_BUTTON_TITLE = 'Метро'
MCK_BUTTON_TITLE = 'МЦК'
MCD_BUTTON_TITLE = 'МЦД'

START_SEARCH_CALLBACK = 'start_search'
MOSCOW_LOCATION_CALLBACK = 'moscow'
MO_LOCATION_CALLBACK = 'mo'
ONLINE_LOCATION_CALLBACK = 'online'

METRO_CALLBACK = 'metro'
MCK_CALLBACK = 'mck'
MCD_CALLBACK = 'mcd'